name: Reuse our other workflow

on: 
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ellisd4/MyFirstWorkflowRepo/.github/workflows/reusable.yml@latest
    with: 
      who-to-greet: '@ellisd4'
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
      
      
